{% set name = "pytest-cookies" %}
{% set version = "0.3.0" %}
{% set sha256 = "7054b5abd87704c3769b46deb65c332fadba80905d4103b0b1e0b4fe8a9a852a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: true

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pytest >=2.8.1
    - cookiecutter >=1.4.0

test:
  imports:
    - pytest_cookies

about:
  home: https://github.com/hackebrot/pytest-cookies
  license: MIT
  license_family: MIT
  # Not included in the sdist yet.
  # Please see the linked PR.
  #
  # https://github.com/hackebrot/pytest-cookies/pull/10
  #
  license_file: LICENSE
  summary: A Pytest plugin for your Cookiecutter templates

extra:
  recipe-maintainers:
    - jakirkham
