# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "K2OaJI+07wYMVO/7suev/+a4Aci5iqCQKouP3j0hWsri9vcsXJVndl449V1d1A+Xi1Jxfm+7C49PXWdMB2ZK1MSmejQjJJdyxM8NV3aPyqG7KoH8EuwhrkqaS3ZpG5vm2BnAD0iQWbyQA2xXK38O66PLM6qJFfP0FNWYGN5MNPIzFAba+y/pbE42z0HYtHFBEz62XZ7Dqdm+xFBq2AEGFdQ7qFfGszTBk4QgvManCBUzR5T25y+mgdM1bEOc6cKgQKmTLZckvReqDnofnvMZXWF1XR9SXxGaY8EJq+jp5lHXMKmuA/vlDdguiPr/lcxnyBY05jU5guArVt+QGiK+YFhF8kSFdBTltUBYzQGXksq2unBQw2XPANMXMgukcpYTVNGz357HZZbMQY8Qj2R7CAVzCQmSqhH1sbP4ab17sJ0BBBQ6GCDm2gtfkEk/DHSime44o5jFu7txDzCn/5LSUzqhGVUqkC7bL839bOk5qFMtsR7itS4o3xKmcaDqd55hRE5mbdDD9kUKbwFcSYIBabuzqRMDJFkoAMZGe+y5teDizauZDKkONMGpM+nhWuWoBKn1QWiqeoCXxdUJd6mVdfWbSz4Ywu0TvYOA/zB3iHSgQpIS4yv9nJjalZhGo5fSeLbATSR89rGN4OA10/I5o94KU5fdaRcvBGigselYLDE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
