travis:
  secure:
    BINSTAR_TOKEN: K2OaJI+07wYMVO/7suev/+a4Aci5iqCQKouP3j0hWsri9vcsXJVndl449V1d1A+Xi1Jxfm+7C49PXWdMB2ZK1MSmejQjJJdyxM8NV3aPyqG7KoH8EuwhrkqaS3ZpG5vm2BnAD0iQWbyQA2xXK38O66PLM6qJFfP0FNWYGN5MNPIzFAba+y/pbE42z0HYtHFBEz62XZ7Dqdm+xFBq2AEGFdQ7qFfGszTBk4QgvManCBUzR5T25y+mgdM1bEOc6cKgQKmTLZckvReqDnofnvMZXWF1XR9SXxGaY8EJq+jp5lHXMKmuA/vlDdguiPr/lcxnyBY05jU5guArVt+QGiK+YFhF8kSFdBTltUBYzQGXksq2unBQw2XPANMXMgukcpYTVNGz357HZZbMQY8Qj2R7CAVzCQmSqhH1sbP4ab17sJ0BBBQ6GCDm2gtfkEk/DHSime44o5jFu7txDzCn/5LSUzqhGVUqkC7bL839bOk5qFMtsR7itS4o3xKmcaDqd55hRE5mbdDD9kUKbwFcSYIBabuzqRMDJFkoAMZGe+y5teDizauZDKkONMGpM+nhWuWoBKn1QWiqeoCXxdUJd6mVdfWbSz4Ywu0TvYOA/zB3iHSgQpIS4yv9nJjalZhGo5fSeLbATSR89rGN4OA10/I5o94KU5fdaRcvBGigselYLDE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
