travis:
  secure:
    BINSTAR_TOKEN: 3EI/0xD9UIOyxO9d4AzP1AxKRWdrA6qqXVddUdpBe7JWbsLI+3sxdoe9Poe/wTMzInmW2LPXjWPgdC8RH6s0hIpTWTVRMieCEyhvV/HePgPUDGgoQRfeAL/gsntSCXQb1tc+eC7NijY/fGKfUZnvMBBfEgkyDwXXuv+6VYTHgEkpoZbxWsoxhhuKb3vmqHf/6Smhs/csbsq/omLc1T4zK5qdDkdWeM6E4EVzoPNPQca51b3u4UPe1Bxl+YNNtU7s9OTtf8B2ClFtchj9X9qar636bfvioRhn/TOcWzq03lMTjWkG9blV98xiwRPRc/1kvoUWWx32W+yAwxDOVTd26v6xyBZx3AJeJ1AbaAojj8REoz+FFYkcSKpw5W6q929mQY1AOKNOEfWGXnXfhOUcpbO1xfX8QmPdNarWUVZjWaoFejiJZ/u75BCOLXHorvjsrZUa+/W8EMTKEs1pSOOqpAZiHAMyllSUFZc9JvmbG04l6kDoZw7pVHvEOSUDWCx3dGi6CWalgyLdJivIg03Xh3fg9pX8fP7zBdn4Tw9x/F/iEiKM1amniQ70+4rEfeLVYCu1X7MCRChl6gZyKYE0oyh891vJZzuSJMLS/2fJ/N/pZ3zTVC0uUQWOyO9xopcwT75seCqwjHRTgdye5MfwlV5KA+uZmHWy6VEUyTfnYFw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
